### PR TITLE
TsumBeta v66

### PR DESCRIPTION
**Pull request by mcs**
### Fixed
- Auto-buying worked only when Tsum Store missions were active.
- Skill for Cabbage Mickey sometimes missed Mickey.
- Unlock level didn't detect 3rd lock icon on 480x800 screen resolution. 

### Added
- Allow script to defer skill activation if fever is active and ends within X seconds 
  (X can be defined in the settings).
- "Claim All" when retrieved hearts do not contain coins anymore. When 3 hearts without coins were collected, the 
  mailbox will be refreshed and new mails will be retrieved until 3 hearts without coins were collected again.
  This will be repeated until 5 or fewer mails were opened before hearts without coins were received. Then "Claim All"
  will be pressed. Intended for when script did not run for more than an hour.
- Documentation of the script settings in the README.
- Root detection on Samsung A20.

### Changed
- Robotmon control panel opens automatically when script is loaded.
- Opening the Robotmon script settings now stops script execution.
- Changed minimal screenshot resolution of pages to a width of 360px in order to make page navigation more safe.
- If script gets started while a game is already open in "pause" mode, the script will continue playing the game instead 
  of leaving it.

### CODE REVIEW

**Comment by mcs** [comment]
Feel free to squash the commits like done before for the master branch in case the request gets approved.

**Comment by Jakesnowy** [comment]
I'm subbed 2x xrobotmon and robotmon-- really hype for this to come through for when I want a tsum tsum "lava lamp" session lol. Thanks all for the effort and contributions :)

**Comment by mcs** [comment]
@Sean-Hsueh @poi5305  Is there a possible problem with the code which blocks the PR?
(please excuse me for having you previously tagged in the wrong PR)

**Comment by mcs** [comment]
I'm closing this for now. All the rebases make this merge request quite ugly. Maybe I will re-create another PR when I got any feedback what went wrong which this one or when I feel like so, but until then, I will take a break.

**Comment by Sean-Hsueh** [comment]
Please feel free to send us a headsup for a prompty response :)
https://www.facebook.com/RobotmonOfficial/

**Pull request closed without merging**
