### PR TITLE
Update friendPageGoTop sleep time to 3.5s

### PR DESCRIPTION
**Pull request by justmaker**
2.5 seconds is not enough for the friend page sliding and stop, it let send heart easily to click on wrong place, I give it extra 1 second to reduce the probability it happens

### CODE REVIEW

**Comment by mcs** [comment]
Hi @justmaker

In this form, the change won't be rolled out to the public because it misses an index.zip file with the updated index.js file. Additionally there currently is #500 open with lots of changes.
As your change looks okay to me, I can offer to merge your change into my pull request and rebuild the zip so it will also contain this change here. Or maybe the person who will merge this and maybe my pull request might run the build.sh script after the merge(s) as a separate commit so that all code changes will be part of the zip.

**Comment by justmaker** [comment]
@mcs It's okay to merge my change into your pull request. Is there anything I need to do?

**Comment by mcs** [comment]
My PR has already been merged. So probably the best way is that you rebase your branch on r2-studio's master branch, then use the build.sh script to create an up-to-date index.zip file. If you push that (either as a single commit or amended into the existing one), then it should be mergable without further conflicts. I don't know if it is technically necessary to increase any version numbers in order to make it available for the public, but probably @poi5305 knows.

If you absolutely cannot run Bash Shell scripts on your computer (no Git Bash and no NPM), then I can cherry pick your commit so it will be part of the next PR when I create one. But that might take some days or weeks until the current feature I work on is stable enough to get released for the public (auto buy boxes).

**Comment by justmaker** [comment]
@mcs I merged latest master and updated the index.zip generated by executing scripts/com.r2studio.TsumBeta/build.sh.

**Comment by mcs** [comment]
@justmaker Looks good for me 👍

**Comment by mcs** [comment]
Your commit efc59615c32b774730826693c3aca26f5ee16138 is now on master and released within version 63, so this PR can be closed.

**Comment by Sean-Hsueh** [comment]
Close per comment by mcs (thanks @justmaker @mcs )

**Pull request closed without merging**
